# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- task: TerraformInstaller@0
  displayName: terraforminstaller
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  displayName: terraforminit
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure-connection'
    backendAzureRmResourceGroupName: 'pipeline'
    backendAzureRmStorageAccountName: 'pipeline12'
    backendAzureRmContainerName: 'container2'
    backendAzureRmKey: 'pipeline.tfstate'
- task: TerraformTaskV3@3
  displayName: terraformplan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'azure-connection'
- task: TerraformTaskV3@3
  displayName: terraformapply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'azure-connection'


  